export const demoBusinesses = [
  {
    id: "demo-business-cafe",
    name: "Örnek Kampüs Kafe",
    category: "Kafe",
    phone: "0286 000 00 01",
    price_info: "Çay 20 TL · Tost 85 TL · Filtre kahve 65 TL",
    has_toilet: true,
    opens_at: "08:00",
    closes_at: "23:00",
    address: "Biga merkez · temsili adres",
  },
  {
    id: "demo-business-kirtasiye",
    name: "Örnek Öğrenci Kırtasiyesi",
    category: "Kırtasiye",
    phone: "0286 000 00 02",
    price_info: "Fotokopi 1 TL/sayfa · çıktı 2 TL/sayfa",
    has_toilet: false,
    opens_at: "08:30",
    closes_at: "20:00",
    address: "Biga İİBF yakını · temsili adres",
  },
  {
    id: "demo-business-yemek",
    name: "Örnek Ev Yemeği Lokantası",
    category: "Yemek",
    phone: "0286 000 00 03",
    price_info: "Günün menüsü 145 TL · çorba 55 TL",
    has_toilet: true,
    opens_at: "11:00",
    closes_at: "21:30",
    address: "Biga çarşı · temsili adres",
  },
  {
    id: "demo-business-camasir",
    name: "Örnek Öğrenci Çamaşırhanesi",
    category: "Hizmet",
    phone: "0286 000 00 04",
    price_info: "Yıkama 90 TL · kurutma 60 TL",
    has_toilet: true,
    opens_at: "09:00",
    closes_at: "22:00",
    address: "Biga merkez · temsili adres",
  },
];

export const demoRoutes = [
  {
    id: "demo-route-campus",
    name: "Merkez – İİBF Kampüsü",
    type: "Otobüs",
    destination: "Biga İİBF",
    first_departure: "07:00",
    last_departure: "22:30",
    price: 20,
    stops: ["Biga Otogar", "Çarşı", "Hükümet Konağı", "İİBF Kampüsü"],
  },
  {
    id: "demo-route-myo",
    name: "Merkez – Biga MYO",
    type: "Servis",
    destination: "Biga MYO",
    first_departure: "07:30",
    last_departure: "18:00",
    price: 25,
    stops: ["Çarşı", "Biga Devlet Hastanesi", "Biga MYO"],
  },
  {
    id: "demo-route-terminal",
    name: "Merkez – Otogar",
    type: "Otobüs",
    destination: "Biga Otogar",
    first_departure: "06:45",
    last_departure: "23:00",
    price: 15,
    stops: ["Cumhuriyet Meydanı", "Çarşı", "Biga Otogar"],
  },
];

export const demoBooks = [
  {
    id: "demo-book-economics",
    title: "Mikro İktisat",
    author: "N. Gregory Mankiw",
    course: "Mikroekonomi",
    condition: "İyi",
    price: 240,
    description: "Kenar notları az, sayfaları temiz.",
    seller_id: null,
    profiles: { name: "Örnek öğrenci" },
  },
  {
    id: "demo-book-accounting",
    title: "Genel Muhasebe",
    author: "Orhan Sevilengül",
    course: "Genel Muhasebe",
    condition: "Çok iyi",
    price: 190,
    description: "Dönem boyunca kapaklı kullanıldı.",
    seller_id: null,
    profiles: { name: "Örnek öğrenci" },
  },
  {
    id: "demo-book-marketing",
    title: "Pazarlama İlkeleri",
    author: "Philip Kotler",
    course: "Pazarlama",
    condition: "Kullanılmış",
    price: 150,
    description: "İçinde birkaç bölüm işaretli.",
    seller_id: null,
    profiles: { name: "Örnek öğrenci" },
  },
];
